### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by dasa** [textmate/requests#1]
It'd be great to have a [TypeScript](http://www.typescriptlang.org) language bundle.

**Comment by sorbits** [comment]
Google informs me that there alrady is such bundle: 
https://github.com/stoffera/textmate-typescript

**Comment by dasa** [comment]
Unfortunately that one hasn't been updated since Oct 22, 2012 so it's sure to be outdated since the language spec was only recently finalized. I was hoping for a supported bundle that would be visible in the Preferences.

**Comment by sorbits** [comment]
If you want the current TypeScript bundle listed in Preferences → 
Bundles then we can certainly add it.

If you want the bundle brought up to date, submit pull requests or if 
you are unsure about how to implement your desired improvements, you can 
open issues using the bundle’s issue tracker or ask at the mailing 
list for help with how to go about improving the bundle.

It’s just not feasible to have me personally responsible for 
supporting the hundreds if not thousands of languages out there.

**Comment by nomaed** [comment]
Microsoft has files that can be bundled up:
https://github.com/Microsoft/TypeScript-TmLanguage

I am not sure how this is done since I'm very new to TextMate, but perhaps it can be added officially.

**Comment by donaldruby** [comment]
If TextMate does not have a bundle for typescript, a large number of users will switch to an editor that supports typescript.

**Comment by stanger** [comment]
I just created a new tmbundle based on https://github.com/Microsoft/TypeScript-TmLanguage. It's largely untested at this point but I have confirmed basic syntax highlighting. You can find it here:

https://github.com/stanger/TypeScript-TextMate

As I venture further into TypeScript I might add more

**Comment by mjustin** [comment]
Is @stanger's bundle at or near a stage where it can be added to the application by default?
