### ISSUE TITLE
Universal binary to support Apple Silicon / ARM M1

### ISSUE THREAD

**Issue by mbirth** [textmate/requests#11]
I'm not sure how much of a hassle it is, but a Universal binary for Intel and ARM architecture would be nice.

Although I must admit, TextMate seems to run with Rosetta 2 just fine.

**Comment by sorbits** [comment]
[Version 2.0.16](https://github.com/textmate/textmate/releases/tag/v2.0.16) is a universal build.

In Preferences → Software Update set “watch for” to “prereleases” to update.
