### ISSUE TITLE
Use the directory of the current tab when opening a file

### ISSUE THREAD

**Issue by jmccaskill** [textmate/requests#12]
I think it would be nice if, when I hit Cmd-O to open a file, it used the directory of the tab I am currently viewing as the working directory, rather than whatever the working directory was from the last time I opened a file.
My typical usage is to open a number of files individually (either from the command line or through the UI, although I don't really use projects), then group them together into one or more windows.  When I need to open another file, I switch to a tab that I think is the closest to the file I want to open, then I hit Cmd-O to open a file.
My expectation is that I can begin searching for the file I want, starting from the directory of the tab I am on.
But really it is the directory of the last file I opened, regardless of whether that happens to be the tab I am on.

**Comment by smokris** [comment]
TextMate already has something kinda like that: with a file already open, you can press Cmd-T (File > Open Quickly…) to pop up a dialog to search in the directory of the already-open file, and open a selected file in another tab.

**Comment by jmccaskill** [comment]
Oh wow, I did not know about that.  Thanks @smokris that works for me.
