### ISSUE TITLE
Fix indentation issues feature at the place the indentation options are set

### ISSUE THREAD

**Issue by dwt** [textmate/requests#2]
Well, I can set how I want the future lines I write in this file should be handled - but whats really missing in this menu (bottom of the window) is an option to make the existing file conform to these settings.

**Comment by sorbits** [comment]
So you want Convert Tabs to Spaces / Spaces to Tabs moved to the indent 
settings submenu?

I’m not sold on such change, though I have a note about a top “scope 
bar” to warn when indent settings do not match current document (with 
a convert button), and this could maybe be triggered if the user changes 
indent settings to no longer match their document.

**Comment by dwt** [comment]
I also wouldn't be sold on _moving_ the feature there. But I do think it sensible to make it easier to find from there.

I really like the Idea of the editor recognizing that it's settings are at odds with what the file is currently formatted in.
