### ISSUE TITLE
Support features of PCRE 8.42 in search 

### ISSUE THREAD

**Issue by giffeler** [textmate/requests#9]
Would be great if the full subset of PCRE 8.42 was supported in search.
In fact, the search can then be used to test complex regular expressions on documents.

**Comment by sorbits** [comment]
TextMate uses the [Onigmo](https://github.com/k-takata/Onigmo) regular expression library (formerly Oniguruma) originally chosen for its UTF-16 support, which is the native encoding of `NSString`.

This library is used both for search (incl. saved macros) and language grammars, so I would need a very good reason for making any changes, as it could break customizations.

If you have specific features that you are missing, please list these, or possibly file feature requests with the Onigmo regular expression library.
